const x = [
  "air", "animal", "apple", "area", "arm", "around", "art", "ask", "away",
  "baby", "back", "bad", "ball", "bank", "base", "bear", "beat", "bed",
  "before", "begin", "behind", "believe", "best", "better", "big", "bird",
  "black", "blue", "boat", "body", "book", "boss", "both", "boy", "break",
  "bright", "bring", "brown", "build", "bus", "business", "butter", "buy",
  "call", "camera", "car", "card", "care", "carry", "case", "cat", "cause",
  "center", "century", "certain", "chair", "chance", "change", "child",
  "choice", "city", "class", "clean", "climb", "clock", "close", "cloud",
  "cold", "color", "come", "company", "complete", "computer", "control",
  "cook", "cool", "corn", "cost", "could", "country", "course", "cover",
  "cow", "create", "cross", "cry", "cup", "current", "cut", "dad", "daily",
  "dance", "danger", "dark", "date", "day", "dead", "deal", "death", "decide",
  "deep", "degree", "describe", "design", "different", "dinner", "direct",
  "discuss", "distance", "dog", "door", "down", "draw", "dream", "dress",
  "drink", "drive", "drop", "dry", "early", "earth", "east", "easy", "eat",
  "edge", "education", "effect", "effort", "egg", "eight", "electric", "else",
  "end", "energy", "enjoy", "enough", "enter", "entire", "equal", "escape",
  "even", "event", "ever", "every", "example", "excellent", "exercise",
  "expect", "experience", "explain", "eye", "face", "fact", "factory", "fail",
  "fall", "family", "famous", "far", "farm", "fast", "father", "favor", "fear",
  "feel", "feeling", "feet", "fell", "female", "few", "field", "fight",
  "figure", "fill", "film", "final", "find", "fine", "finish", "fire", "first",
  "fish", "five", "floor", "flower", "fly", "follow", "food", "foot", "forest",
  "forget", "form", "forward", "found", "free", "fresh", "friend", "front",
  "fruit", "full", "fun", "future", "gain", "game", "garden", "gave", "get",
  "girl", "give", "glass", "go", "goal", "god", "good", "government", "great",
  "green", "grow", "guess", "gun", "guy", "hair", "half", "hand", "happen",
  "happy", "hard", "hat", "hate", "head", "health", "hear", "heart", "heat",
  "heavy", "help", "high", "hill", "history", "hit", "hold", "hole", "home",
  "hope", "horse", "hot", "hotel", "hour", "house", "huge", "human", "hundred",
  "hungry", "hunt", "hurt", "ice", "idea", "important", "improve", "include",
  "industry", "information", "inside", "instead", "interest", "into", "issue",
  "job", "join", "juice", "jump", "just", "keep", "key", "kid", "kind", "king",
  "kiss", "kitchen", "know", "lack", "lady", "lake", "land", "large", "last",
  "late", "laugh", "law", "lay", "lead", "learn", "least", "leave", "left",
  "leg", "less", "letter", "level", "lie", "life", "light", "like", "line",
  "lion", "list", "little", "live", "local", "long", "look", "lose", "loss",
  "lot", "loud", "love", "low", "machine", "main", "make", "man", "manage",
  "many", "map", "mark", "market", "match", "matter", "may", "meal", "mean",
  "measure", "meat", "media", "medical", "meet", "memory", "middle", "might",
  "mile", "milk", "million", "mind", "minute", "mirror", "miss", "mistake",
  "mix", "mobile", "model", "moment", "money", "month", "moon", "more",
  "morning", "mother", "motion", "mountain", "mouth", "move", "movie", "much",
  "music", "must", "name", "nation", "nature", "near", "necessary", "need",
  "network", "never", "new", "next", "nice", "night", "nine", "nobody", "noise",
  "north", "nose", "note", "nothing", "notice", "number", "ocean", "offer",
  "often", "oil", "okay", "old", "once", "only", "open", "operation", "opinion",
  "order", "other", "outside", "over", "own", "page", "pain", "paint", "pair",
  "pan", "paper", "parent", "park", "part", "party", "pass", "past", "pay",
  "peace", "pen", "people", "perfect", "period", "person", "phone", "photo",
  "phrase", "picture", "piece", "pig", "place", "plain", "plan", "plane",
  "plant", "play", "player", "please", "point", "police", "poor", "popular",
  "position", "possible", "power", "practice", "prepare", "present", "pretty",
  "price", "problem", "process", "produce", "product", "program", "project",
  "property", "protect", "prove", "public", "pull", "purpose", "push", "put",
  "quality", "question", "quick", "quiet", "quite", "race", "radio", "rain",
  "raise", "range", "rate", "reach", "read", "ready", "real", "really", "reason",
  "receive", "record", "red", "reduce", "region", "relate", "remain", "remember",
  "remove", "report", "rest", "result", "return", "rich", "right", "ring",
  "river", "road", "rock", "role", "room", "round", "route", "rule", "run",
  "sad", "safe", "sale", "same", "sand", "say", "scale", "school", "science",
  "score", "sea", "search", "season", "seat", "second", "secret", "section",
  "see", "seek", "seem", "sell", "send", "sense", "series", "service", "set",
  "several", "shape", "share", "sheep", "ship", "shoe", "shop", "short",
  "should", "show", "side", "sight", "sign", "since", "sing", "single", "sister",
  "sit", "site", "situation", "size", "skill", "sky", "sleep", "small", "smile",
  "smoke", "so", "social", "soft", "soldier", "somebody", "something", "son",
  "song", "soon", "sorry", "sound", "south", "space", "speak", "special",
  "speed", "spend", "sport", "spring", "staff", "stage", "stand", "star",
  "start", "state", "station", "stay", "step", "still", "stone", "stop", "store",
  "story", "straight", "street", "strong", "structure", "student", "study",
  "subject", "success", "such", "sudden", "sugar", "summer", "sun", "supper",
  "sure", "surface", "system", "table", "take", "talk", "tall", "tape", "task",
  "taste", "tea", "teach", "team", "technology", "tell", "temperature", "ten",
  "test", "than", "thank", "their", "them", "then", "there", "these", "they",
  "thing", "think", "third", "those", "though", "thought", "three", "through",
  "thus", "time", "today", "together", "tomorrow", "tonight", "too", "top",
  "total", "touch", "tour", "town", "trade", "train", "travel", "treat", "tree",
  "trip", "true", "trust", "try", "turn", "tv", "twelve", "twenty", "two",
  "type", "under", "understand", "unit", "university", "until", "up", "upon",
  "use", "usual", "value", "various", "version", "very", "video", "view",
  "village", "visit", "voice", "wait", "walk", "wall", "want", "war", "warm",
  "was", "wash", "watch", "water", "way", "weak", "wealth", "weapon", "week",
  "weight", "well", "west", "what", "when", "where", "while", "white", "whole",
  "why", "wide", "wife", "will", "win", "wind", "window", "winter", "wish",
  "woman", "wonder", "wood", "word", "work", "world", "write", "wrong", "year",
  "yes", "yet", "young", "your", "youth", "zoo"
];

let outp = x[Math.floor(Math.random() * x.length)]
console.log(outp);